<?php

/*
 * This file is part of sad_spirit/pg_gateway package
 *
 * (c) Alexey Borzov <avb@php.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace sad_spirit\pg_gateway\metadata;

/**
 * Represents information about a FOREIGN KEY (referential integrity constraint) in the DB
 *
 * @implements \IteratorAggregate<string, string>
 */
final readonly class ForeignKey implements \IteratorAggregate
{
    public function __construct(
        private TableName $childTable,
        /** @var string[] */
        private array $childColumns,
        private TableName $referencedTable,
        /** @var string[] */
        private array $referencedColumns,
        private string $constraintName
    ) {
    }

    /**
     * Returns the name of the child table (the one to which the FOREIGN KEY constraint was added)
     */
    public function getChildTable(): TableName
    {
        return $this->childTable;
    }

    /**
     * Returns the name of the referenced / parent table (the one mentioned in the REFERENCES clause of FOREIGN KEY)
     */
    public function getReferencedTable(): TableName
    {
        return $this->referencedTable;
    }

    /**
     * Returns the names of the columns in the child table
     */
    public function getChildColumns(): array
    {
        return $this->childColumns;
    }

    /**
     * Returns the names of the columns in the referenced table
     */
    public function getReferencedColumns(): array
    {
        return $this->referencedColumns;
    }

    /**
     * Returns the name of the FOREIGN KEY constraint
     *
     * The name is always available, autogenerated by Postgres if not given explicitly.
     */
    public function getConstraintName(): string
    {
        return $this->constraintName;
    }

    /**
     * {@inheritDoc}
     *
     * Iterates over a mapping ['child column' => 'referenced column']
     */
    public function getIterator(): \ArrayIterator
    {
        return new \ArrayIterator(\array_combine($this->childColumns, $this->referencedColumns));
    }

    /**
     * Returns whether a foreign key is recursive, i.e. refers back to the same table
     */
    public function isRecursive(): bool
    {
        return $this->childTable->equals($this->referencedTable);
    }
}
