<?php

/*
 * This file is part of sad_spirit/pg_gateway:
 * Table Data Gateway for Postgres - auto-converts types, allows raw SQL, supports joins between gateways
 *
 * (c) Alexey Borzov <avb@php.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace sad_spirit\pg_gateway\metadata;

/**
 * Represents information about a FOREIGN KEY (referential integrity constraint) in the DB
 *
 * @implements \IteratorAggregate<string, string>
 */
final readonly class ForeignKey implements \IteratorAggregate
{
    /**
     * @param TableName $childTable        Name of the child table
     *                                     (the one to which the FOREIGN KEY constraint was added)
     * @param string[]  $childColumns      Names of the columns in the child table
     * @param TableName $referencedTable   Name of the referenced / parent table
     *                                     (the one mentioned in the REFERENCES clause of FOREIGN KEY)
     * @param string[]  $referencedColumns Names of the columns in the referenced table
     * @param string    $constraintName    Name of the FOREIGN KEY constraint (always available,
     *                                     autogenerated by Postgres if not given explicitly)
     */
    public function __construct(
        public TableName $childTable,
        public array $childColumns,
        public TableName $referencedTable,
        public array $referencedColumns,
        public string $constraintName
    ) {
    }

    /**
     * {@inheritDoc}
     *
     * Iterates over a mapping ['child column' => 'referenced column']
     *
     * @return \ArrayIterator<string, string>
     */
    public function getIterator(): \ArrayIterator
    {
        return new \ArrayIterator(\array_combine($this->childColumns, $this->referencedColumns));
    }

    /**
     * Returns whether a foreign key is recursive, i.e. refers back to the same table
     */
    public function isRecursive(): bool
    {
        return $this->childTable->equals($this->referencedTable);
    }
}
