<?php

/*
 * This file is part of sad_spirit/pg_gateway package
 *
 * (c) Alexey Borzov <avb@php.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace sad_spirit\pg_gateway\metadata;

/**
 * Represents information about a FOREIGN KEY (referential integrity constraint) in the DB
 *
 * @implements \IteratorAggregate<string, string>
 */
class ForeignKey implements \IteratorAggregate
{
    private TableName $childTable;
    private TableName $referencedTable;
    /** @var string[] */
    private array $childColumns;
    /** @var string[] */
    private array $referencedColumns;
    private string $constraintName;

    public function __construct(
        TableName $childTable,
        array $childColumns,
        TableName $referencedTable,
        array $referencedColumns,
        string $constraintName
    ) {
        $this->childTable = $childTable;
        $this->childColumns = $childColumns;
        $this->referencedTable = $referencedTable;
        $this->referencedColumns = $referencedColumns;
        $this->constraintName = $constraintName;
    }

    /**
     * Returns the name of the child table (the one to which the FOREIGN KEY constraint was added)
     *
     * @return TableName
     */
    public function getChildTable(): TableName
    {
        return $this->childTable;
    }

    /**
     * Returns the name of the referenced / parent table (the one mentioned in the REFERENCES clause of FOREIGN KEY)
     *
     * @return TableName
     */
    public function getReferencedTable(): TableName
    {
        return $this->referencedTable;
    }

    /**
     * Returns the names of the columns in the child table
     *
     * @return array
     */
    public function getChildColumns(): array
    {
        return $this->childColumns;
    }

    /**
     * Returns the names of the columns in the referenced table
     *
     * @return array
     */
    public function getReferencedColumns(): array
    {
        return $this->referencedColumns;
    }

    /**
     * Returns the name of the FOREIGN KEY constraint
     *
     * The name is always available, autogenerated by Postgres if not given explicitly.
     *
     * @return string
     */
    public function getConstraintName(): string
    {
        return $this->constraintName;
    }

    /**
     * {@inheritDoc}
     *
     * Iterates over a mapping ['child column' => 'referenced column']
     *
     * @return \ArrayIterator
     */
    public function getIterator(): \ArrayIterator
    {
        return new \ArrayIterator(\array_combine($this->childColumns, $this->referencedColumns));
    }

    /**
     * Returns whether a foreign key is recursive, i.e. refers back to the same table
     *
     * @return bool
     */
    public function isRecursive(): bool
    {
        return $this->childTable->equals($this->referencedTable);
    }
}
